name: Bazel ROS Continuous Integration

on: [push, pull_request, pull_request_target]


jobs:
  bazel_build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ros:rolling-ros-base-focal
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel
      - name: Test drake_ros_core
        run: bazel build //...
        working-directory: outdoor_slam_ros2
